print("Enter the mass of the person in kilograms:", end=" ")
mass=float(input())
print("Enter the height of the person in metres:", end=" ")
height=float(input())
bmi=mass/(height*height)
print("The Body Mass Index of the person is:", bmi)
