print("Keep pressing enter key to get jokes")
input()
print()
print("Why couldn't the astronaut book a room on the moon? A. It was full!")
input()
print()
print("What do scientists use to freshen their breath? A. Experi-mints! ")
input()
print()
print("")
input()
print()
print("")
input()
print()
print("")
input()
print()
print("")
input()
print()
print("")
